version: '3.8'

services:
  postgres:
    image: postgres:17.2
    container_name: postgres-db
    ports:
      - 5438:5432
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - bothub

volumes:
  postgres_data:

networks:
  bothub:
